services:
  3xui:
    image: ${XUI_IMAGE:-ghcr.io/mhsanaei/3x-ui:latest}
    container_name: ${XUI_CONTAINER:-3xui}
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./data/db:/etc/x-ui
      - ./data/cert:/root/cert
      - ./data/backups:/backups
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
      XUI_ENABLE_FAIL2BAN: "true"
      XUI_LOG_LEVEL: ${XUI_LOG_LEVEL:-info}
      XUI_PORT: ${PANEL_PORT:-2053}
      XUI_INIT_WEB_BASE_PATH: "/${WEB_BASE_PATH:-panel}"
    restart: unless-stopped

  caddy-site:
    image: caddy:2-alpine
    container_name: ${CADDY_CONTAINER:-3xui_site}
    profiles:
      - site
    ports:
      - "${SITE_HTTP_PORT:-80}:80"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./site:/usr/share/caddy:ro
      - ./data/caddy:/data
      - ./data/caddy-config:/config
    restart: unless-stopped

